"""
satorip2p/protocol/

Protocol implementations for Satori P2P networking.
"""

from .subscriptions import SubscriptionManager
from .message_store import MessageStore
from .messages import serialize_message, deserialize_message
from .rendezvous import RendezvousManager, RendezvousRegistration
from .peer_registry import PeerRegistry, PeerAnnouncement
from .stream_registry import StreamRegistry, StreamDefinition, StreamClaim
from .oracle_network import OracleNetwork, Observation, OracleRegistration
from .prediction_protocol import PredictionProtocol, Prediction, PredictionScore
from .rewards import (
    SatoriScorer,
    RewardCalculator,
    RoundDataStore,
    PredictionInput,
    ScoreBreakdown,
    ScoringResult,
    RewardEntry,
    RoundSummary,
    InhibitorResult,
    score_prediction,
    verify_score,
    verify_reward_claim,
    get_round_boundaries,
    # Pool reward distribution
    PoolRewardDistributor,
    EnhancedRewardCalculator,
    LenderReward,
    PoolRewardSummary,
    DEFAULT_OPERATOR_FEE,
    MAX_OPERATOR_FEE,
    # Role multipliers
    NodeRoles,
    get_role_multiplier,
    ROLE_BONUS_RELAY,
    ROLE_BONUS_ORACLE,
    ROLE_BONUS_SIGNER,
    ROLE_MULTIPLIER_CAP,
    # Stake bonuses (prediction-centric model)
    MIN_STAKE,
    STAKE_BONUS_INTERVAL,
    STAKE_BONUS_PER_INTERVAL,
    STAKE_BONUS_CAP,
    calculate_stake_bonus,
    get_total_multiplier,
    # Referral bonuses
    REFERRAL_BONUS_BRONZE,
    REFERRAL_BONUS_SILVER,
    REFERRAL_BONUS_GOLD,
    REFERRAL_BONUS_PLATINUM,
    REFERRAL_BONUS_DIAMOND,
    REFERRAL_BONUS_CAP,
    REFERRAL_TIER_BRONZE,
    REFERRAL_TIER_SILVER,
    REFERRAL_TIER_GOLD,
    REFERRAL_TIER_PLATINUM,
    REFERRAL_TIER_DIAMOND,
    calculate_referral_bonus,
    get_referral_tier,
    # Pool diversity bonuses (decentralization incentive)
    POOL_DIVERSITY_TIER_SMALL,
    POOL_DIVERSITY_TIER_MEDIUM,
    POOL_DIVERSITY_TIER_LARGE,
    POOL_DIVERSITY_BONUS_SMALL,
    POOL_DIVERSITY_BONUS_MEDIUM,
    POOL_DIVERSITY_BONUS_LARGE,
    POOL_DIVERSITY_BONUS_CAP,
    calculate_pool_diversity_bonus,
    get_pool_diversity_tier,
)
from .reward_address import (
    RewardAddressManager,
    RewardAddressRecord,
    RewardAddressCache,
    DHT_REWARD_ADDR_PREFIX,
    REWARD_ADDR_TOPIC,
)
from .referral import (
    ReferralManager,
    Referral,
    ReferrerStats,
    ReferralTierAchievement,
    DHT_REFERRAL_PREFIX,
    DHT_REFERRER_PREFIX,
    REFERRAL_TOPIC,
    REFERRAL_TIERS,
    REFERRAL_TIER_ORDER,
)
from .lending import LendingManager, PoolConfig, LendRegistration
from .delegation import DelegationManager, DelegationRecord, CharityUpdate
from .signer import (
    SignerNode,
    SignatureRequest,
    SignatureResponse,
    SigningResult,
    create_multisig_address,
    create_multisig_redeem_script,
    is_authorized_signer,
    get_signer_count,
    get_treasury_address,
    AUTHORIZED_SIGNERS_CONFIG,
    AUTHORIZED_SIGNERS,
    AUTHORIZED_SIGNER_PUBKEYS,
    TREASURY_MULTISIG_ADDRESS,
)
from .donation import (
    DonationManager,
    TreasuryDonation,
    DonorStats,
    TierAchievement,
    DONATION_TIERS,
    TIER_ORDER,
    EPOCH_DURATION,
    ROUND_DURATION,
    get_epoch_from_timestamp,
    get_round_from_timestamp,
    get_epoch_boundaries,
    get_donation_round_boundaries,
    get_tier_for_amount,
    get_tier_threshold,
    get_next_tier,
    get_progress_to_next_tier,
)
from .alerts import (
    TreasuryAlertManager,
    TreasuryAlert,
    TreasuryStatus,
    AlertHistoryEntry,
    AlertAction,
    AlertSeverity,
    AlertType,
    EVR_FEES,
    TOPIC_TREASURY_ALERTS,
    TOPIC_DISTRIBUTION_ALERTS,
    TOPIC_SYSTEM_ALERTS,
    check_evr_for_operation,
)
from .deferred_rewards import (
    DeferredRewardsManager,
    DeferredReward,
    DeferredRewardsSummary,
    RoundDeferral,
    DeferralReason,
    should_defer_distribution,
)
from .pricing import (
    SafeTradePriceProvider,
    PriceQuote,
    TickerData,
    get_price_provider,
    get_exchange_rates,
    get_evr_satori_ratio,
    calculate_satori_reward,
    SAFETRADE_EVR_USDT,
    SAFETRADE_SATORI_USDT,
    DEFAULT_EVR_USD,
    DEFAULT_SATORI_USD,
)
from .versioning import (
    ProtocolVersion,
    VersionNegotiator,
    FeatureFlag,
    FeatureSet,
    VersionInfo,
    PeerVersionTracker,
    PROTOCOL_VERSION,
    MIN_SUPPORTED_VERSION,
    CURRENT_VERSION,
    MIN_VERSION,
    VERSION_FEATURES,
    COMPATIBILITY_MATRIX,
    get_version_info,
    get_breaking_changes,
    get_supported_versions,
    get_current_version,
    get_current_features,
    check_compatibility,
    add_version_to_message,
    get_message_version,
    is_message_compatible,
)
from .storage import (
    RedundantStorage,
    StorageManager,
    DeferredRewardsStorage,
    AlertStorage,
    StoredDeferredReward,
    StoredAlert,
    MemoryBackend,
    FileBackend,
    DHTBackend,
    DHT_DEFERRED_REWARDS_PREFIX,
    DHT_ALERT_HISTORY_PREFIX,
    DHT_STORAGE_PREFIX,
    DEFAULT_STORAGE_DIR,
)
from .bandwidth import (
    BandwidthTracker,
    QoSManager,
    QoSPolicy,
    MessagePriority,
    BandwidthMetrics,
    WindowedCounter,
    RateLimiter,
    create_qos_manager,
    get_priority_for_message_type,
    DEFAULT_GLOBAL_BYTES_PER_SECOND,
    DEFAULT_TOPIC_BYTES_PER_SECOND,
    DEFAULT_PEER_BYTES_PER_SECOND,
    DEFAULT_GLOBAL_MESSAGES_PER_SECOND,
    DEFAULT_TOPIC_MESSAGES_PER_SECOND,
    DEFAULT_PEER_MESSAGES_PER_SECOND,
)

__all__ = [
    "SubscriptionManager",
    "MessageStore",
    "serialize_message",
    "deserialize_message",
    "RendezvousManager",
    "RendezvousRegistration",
    "PeerRegistry",
    "PeerAnnouncement",
    "StreamRegistry",
    "StreamDefinition",
    "StreamClaim",
    "OracleNetwork",
    "Observation",
    "OracleRegistration",
    "PredictionProtocol",
    "Prediction",
    "PredictionScore",
    # Rewards (Phase 5)
    "SatoriScorer",
    "RewardCalculator",
    "RoundDataStore",
    "PredictionInput",
    "ScoreBreakdown",
    "ScoringResult",
    "RewardEntry",
    "RoundSummary",
    "InhibitorResult",
    "score_prediction",
    "verify_score",
    "verify_reward_claim",
    "get_round_boundaries",
    # Pool Reward Distribution
    "PoolRewardDistributor",
    "EnhancedRewardCalculator",
    "LenderReward",
    "PoolRewardSummary",
    "DEFAULT_OPERATOR_FEE",
    "MAX_OPERATOR_FEE",
    # Role Multipliers
    "NodeRoles",
    "get_role_multiplier",
    "ROLE_BONUS_RELAY",
    "ROLE_BONUS_ORACLE",
    "ROLE_BONUS_SIGNER",
    "ROLE_MULTIPLIER_CAP",
    # Stake Bonuses (Prediction-Centric Model)
    "MIN_STAKE",
    "STAKE_BONUS_INTERVAL",
    "STAKE_BONUS_PER_INTERVAL",
    "STAKE_BONUS_CAP",
    "calculate_stake_bonus",
    "get_total_multiplier",
    # Referral Bonuses
    "REFERRAL_BONUS_BRONZE",
    "REFERRAL_BONUS_SILVER",
    "REFERRAL_BONUS_GOLD",
    "REFERRAL_BONUS_PLATINUM",
    "REFERRAL_BONUS_DIAMOND",
    "REFERRAL_BONUS_CAP",
    "REFERRAL_TIER_BRONZE",
    "REFERRAL_TIER_SILVER",
    "REFERRAL_TIER_GOLD",
    "REFERRAL_TIER_PLATINUM",
    "REFERRAL_TIER_DIAMOND",
    "calculate_referral_bonus",
    "get_referral_tier",
    # Pool Diversity Bonuses (Decentralization Incentive)
    "POOL_DIVERSITY_TIER_SMALL",
    "POOL_DIVERSITY_TIER_MEDIUM",
    "POOL_DIVERSITY_TIER_LARGE",
    "POOL_DIVERSITY_BONUS_SMALL",
    "POOL_DIVERSITY_BONUS_MEDIUM",
    "POOL_DIVERSITY_BONUS_LARGE",
    "POOL_DIVERSITY_BONUS_CAP",
    "calculate_pool_diversity_bonus",
    "get_pool_diversity_tier",
    # Reward Address (Custom Payouts)
    "RewardAddressManager",
    "RewardAddressRecord",
    "RewardAddressCache",
    "DHT_REWARD_ADDR_PREFIX",
    "REWARD_ADDR_TOPIC",
    # Referral System
    "ReferralManager",
    "Referral",
    "ReferrerStats",
    "ReferralTierAchievement",
    "DHT_REFERRAL_PREFIX",
    "DHT_REFERRER_PREFIX",
    "REFERRAL_TOPIC",
    "REFERRAL_TIERS",
    "REFERRAL_TIER_ORDER",
    # Lending (Pool Operations)
    "LendingManager",
    "PoolConfig",
    "LendRegistration",
    # Delegation (Proxy Operations)
    "DelegationManager",
    "DelegationRecord",
    "CharityUpdate",
    # Signer (Multi-sig)
    "SignerNode",
    "SignatureRequest",
    "SignatureResponse",
    "SigningResult",
    "create_multisig_address",
    "create_multisig_redeem_script",
    "is_authorized_signer",
    "get_signer_count",
    "get_treasury_address",
    "AUTHORIZED_SIGNERS_CONFIG",
    "AUTHORIZED_SIGNERS",
    "AUTHORIZED_SIGNER_PUBKEYS",
    "TREASURY_MULTISIG_ADDRESS",
    # Donation (Treasury)
    "DonationManager",
    "TreasuryDonation",
    "DonorStats",
    "TierAchievement",
    "DONATION_TIERS",
    "TIER_ORDER",
    "EPOCH_DURATION",
    "ROUND_DURATION",
    "get_epoch_from_timestamp",
    "get_round_from_timestamp",
    "get_epoch_boundaries",
    "get_donation_round_boundaries",
    "get_tier_for_amount",
    "get_tier_threshold",
    "get_next_tier",
    "get_progress_to_next_tier",
    # Alerts (Treasury Edge Cases)
    "TreasuryAlertManager",
    "TreasuryAlert",
    "TreasuryStatus",
    "AlertHistoryEntry",
    "AlertAction",
    "AlertSeverity",
    "AlertType",
    "EVR_FEES",
    "TOPIC_TREASURY_ALERTS",
    "TOPIC_DISTRIBUTION_ALERTS",
    "TOPIC_SYSTEM_ALERTS",
    "check_evr_for_operation",
    # Deferred Rewards
    "DeferredRewardsManager",
    "DeferredReward",
    "DeferredRewardsSummary",
    "RoundDeferral",
    "DeferralReason",
    "should_defer_distribution",
    # Pricing (SafeTrade)
    "SafeTradePriceProvider",
    "PriceQuote",
    "TickerData",
    "get_price_provider",
    "get_exchange_rates",
    "get_evr_satori_ratio",
    "calculate_satori_reward",
    "SAFETRADE_EVR_USDT",
    "SAFETRADE_SATORI_USDT",
    "DEFAULT_EVR_USD",
    "DEFAULT_SATORI_USD",
    # Protocol Versioning
    "ProtocolVersion",
    "VersionNegotiator",
    "FeatureFlag",
    "FeatureSet",
    "VersionInfo",
    "PeerVersionTracker",
    "PROTOCOL_VERSION",
    "MIN_SUPPORTED_VERSION",
    "CURRENT_VERSION",
    "MIN_VERSION",
    "VERSION_FEATURES",
    "COMPATIBILITY_MATRIX",
    "get_version_info",
    "get_breaking_changes",
    "get_supported_versions",
    "get_current_version",
    "get_current_features",
    "check_compatibility",
    "add_version_to_message",
    "get_message_version",
    "is_message_compatible",
    # Storage Redundancy
    "RedundantStorage",
    "StorageManager",
    "DeferredRewardsStorage",
    "AlertStorage",
    "StoredDeferredReward",
    "StoredAlert",
    "MemoryBackend",
    "FileBackend",
    "DHTBackend",
    "DHT_DEFERRED_REWARDS_PREFIX",
    "DHT_ALERT_HISTORY_PREFIX",
    "DHT_STORAGE_PREFIX",
    "DEFAULT_STORAGE_DIR",
    # Bandwidth Accounting & QoS
    "BandwidthTracker",
    "QoSManager",
    "QoSPolicy",
    "MessagePriority",
    "BandwidthMetrics",
    "WindowedCounter",
    "RateLimiter",
    "create_qos_manager",
    "get_priority_for_message_type",
    "DEFAULT_GLOBAL_BYTES_PER_SECOND",
    "DEFAULT_TOPIC_BYTES_PER_SECOND",
    "DEFAULT_PEER_BYTES_PER_SECOND",
    "DEFAULT_GLOBAL_MESSAGES_PER_SECOND",
    "DEFAULT_TOPIC_MESSAGES_PER_SECOND",
    "DEFAULT_PEER_MESSAGES_PER_SECOND",
]
